# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    avoid_annotating_with_dynamic: true
    avoid_catches_without_on_clauses: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    cascade_invocations: true
    combinators_ordering: true
    dangling_library_doc_comments: true
    directives_ordering: true
    empty_catches: true
    enable_null_safety: true
    eol_at_end_of_file: true
    file_names: true
    flutter_style_todos: true
    library_prefixes: true
    lines_longer_than_80_chars: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_interpolation_to_compose_strings: true
    prefer_null_aware_method_calls: true
    require_trailing_commas: true
    sort_child_properties_last: true
    avoid_relative_lib_imports: true
    depend_on_referenced_packages: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
